#!/usr/bin/env python3
"""
Build-time codegen: read CRIU's cloud-instance NIC CSV and emit a C
header with a sorted static array consumed by auto_nic.c.

Usage: scripts/gen_nic_table.py <input.csv> > <output.h>

Sort order (provider, itype) matches bsearch(3) usage in auto_nic.c —
do not change without updating the comparator.
"""
import sys


def main():
    if len(sys.argv) != 2:
        sys.stderr.write(
            "usage: gen_nic_table.py <input.csv>  (output to stdout)\n"
        )
        sys.exit(2)

    rows = []
    with open(sys.argv[1]) as f:
        for lineno, raw in enumerate(f, 1):
            line = raw.strip()
            if not line or line.startswith("#"):
                continue
            parts = [p.strip() for p in line.split(",")]
            if len(parts) != 3:
                sys.stderr.write(
                    f"{sys.argv[1]}:{lineno}: bad row (need 3 cols): {line}\n"
                )
                sys.exit(1)
            provider, itype, mbps_s = parts
            try:
                mbps = int(mbps_s)
            except ValueError:
                sys.stderr.write(
                    f"{sys.argv[1]}:{lineno}: mbps not int: {mbps_s}\n"
                )
                sys.exit(1)
            rows.append((provider, itype, mbps))

    rows.sort(key=lambda r: (r[0], r[1]))

    out = sys.stdout.write
    out("/* AUTO-GENERATED by scripts/gen_nic_table.py — do not edit. */\n")
    out("/* Regenerates from criu/contrib/nic-table.csv on rebuild.  */\n")
    out("#ifndef __CRIU_NIC_TABLE_GEN_H__\n")
    out("#define __CRIU_NIC_TABLE_GEN_H__\n")
    out("\n")
    out("struct nic_table_row {\n")
    out("\tconst char *provider;\n")
    out("\tconst char *itype;\n")
    out("\tint nic_mbps;\n")
    out("};\n")
    out("\n")
    out(f"#define NIC_TABLE_N {len(rows)}\n")
    out(
        "static const struct nic_table_row "
        "NIC_TABLE[NIC_TABLE_N] = {\n"
    )
    for provider, itype, mbps in rows:
        out(f'\t{{ "{provider}", "{itype}", {mbps} }},\n')
    out("};\n")
    out("\n")
    out("#endif /* __CRIU_NIC_TABLE_GEN_H__ */\n")


if __name__ == "__main__":
    main()
